# Generated by Django 6.0 on 2026-01-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('educator', 'Educator')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='domain',
            field=models.CharField(default='healthcare', max_length=50),
        ),
    ]
